coverage:
  precision: 0
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 90%
        threshold: 1%

ignore:
  - "**/mocks"
  - "**/*.gen.go"
  - "**/*.pb.go"
  - "**/.gen"

comment:
  layout: "newheader, diff, flags, files"  # show component info in the PR comment
  require_head: true
  show_carryforward_flags: true

flags:
  pkg:
    carryforward: true
    paths:
      - pkg
