name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # run daily at midnight

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: moonwayio/ci/go/action.yaml@main
        with:
          go-version-file: go.mod
      - name: Run go mod tidy
        run: go mod tidy

      - name: Run modcheck
        run: make modcheck

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          install-mode: goinstall
          version: latest
          args: --timeout 5m

  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: moonwayio/ci/go/action.yaml@main
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test-ci

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  vulncheck:
      name: Vulncheck
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v5

        - name: Setup Go
          uses: moonwayio/ci/go/action.yaml@main
          with:
            go-version-file: go.mod

        - name: Run govulncheck
          run: make vuln.check
